### ISSUE TITLE
Búsqueda de Organizaciones/proyectos

### ISSUE THREAD

**Issue by carla-b** [datasketch/exploralatam#2]
En el link: https://exploralatam.netlify.com/organizaciones/  no se ve ningun dato; entiendo que estan trabajando en el buscador, pero estaria bien que al menos aparezca una lista inicial. Sino, es muy dificil "buscar". 

Lo mismo con proyectos (https://exploralatam.netlify.com/proyectos/)

No veo ningun dato, por eso, dificl chequear si hay errores.

**Comment by carla-b** [comment]
Tambien: ademas de la lista inicial que  muestre a algunas orgs/proyectos, estaria bien tener a los tags por los cuales se puede buscar orgs/proyectos mas visibles.

**Comment by jpmarindiaz** [comment]
El buscador ya quedó activado de nuevo. Dejo el issue abierto para mejorar la búsqueda con tags

**Comment by ddazal** [comment]
Closed in 3c7b79dc3e14ca60b6bf30478f30e7be1eb88160
