### ISSUE TITLE
Agregar mailchimp a la leyenda del newsletter

### ISSUE THREAD

**Issue by carla-b** [datasketch/exploralatam#4]
Una cosa que comentamos es armar una base para alimentar el newsletter y blogs. Hoy, en la pag principal, aparece esto: "PARA MANTENERSE AL TANTO CON EL PROYECTO, LAS INICIATIVAS DE DATOS ABIERTOS Y LA TECNOLOGÍA CÍVICA EN AMÉRICA LATINA, SÍGANOS EN TWITTER @IDATOSABIERTOS"

Sugiero cambiar eso a unirse al newsletter ahi, y agregar a quienes se vayan suscribiendo. Por ejemplo "Subscribe to our mailing list and receive our news items, blogposts, and events direct to your inbox" (como se diga mejor en espaniol). 

Si no queremos crear un lista para el Exploralatam, se podria unir al mailchiomp de ILDA. Aca, verlo con Fabrizio?

**Comment by carla-b** [comment]
Relacionado: a donde va el form "contacto"? (quien lo recibe? Va al mailchimp de ILDA? o a alguien en particular?

**Comment by ddazal** [comment]
Closed in c6dc47fae75b40def066019e904ceadc84b6cbc2
